version: "3.8"

services:
  node:
    container_name: "${APP_NAME}_app"
    ports:
      - ${APP_PORT}:${APP_PORT}
    image: "node:14"
    tty: true
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app