version: "3.8"

services:
  initial:
    container_name: "${APP_NAME}_initial"
    ports:
      - ${APP_PORT}:${APP_PORT}
    build:
      context: ./
      dockerfile: docker-compose/node-initial/node.dockerfile
      args:
        USER: ${APP_USER}
        UID: ${APP_UID}
    tty: true
    volumes:
      - ./public/:${WORK_DIRECTORY}
      - ~/.ssh:/home/${APP_USER}/.ssh
    working_dir: ${WORK_DIRECTORY}